# Generated by Django 4.1.3 on 2022-11-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_services_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
