# Generated by Django 4.1.3 on 2022-12-02 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicehistory',
            options={'verbose_name_plural': 'service history'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'services'},
        ),
    ]
